version: '3.7'

services:
  # databases
  db1:
    image: mysql:5.7
    restart: always
  db2:
    image: mysql:5.7
    restart: always

  # wordpress
  wp1:
    image: wordpress:5-fpm
    restart: always
    volumes:
      - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  wp2:
    image: wordpress:5-fpm
    restart: always
    volumes:
      - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  # nginx
  web:
    image: nginx
    restart: always