version: '3.7'

services:
  # databases
  db1:
    environment:
      MYSQL_ROOT_PASSWORD: wordpresspw_root1
      MYSQL_DATABASE: wordpressdb1
      MYSQL_USER: wordpressuser1
      MYSQL_PASSWORD: wordpresspw1
    volumes:
      - ./db1:/var/lib/mysql
  db2:
    environment:
      MYSQL_ROOT_PASSWORD: wordpresspw_root2
      MYSQL_DATABASE: wordpressdb2
      MYSQL_USER: wordpressuser2
      MYSQL_PASSWORD: wordpresspw2
    volumes:
      - ./db2:/var/lib/mysql

  # wordpress
  wp1:
    depends_on:
      - db1
    environment:
      WORDPRESS_DB_HOST: db1:3306
      WORDPRESS_DB_USER: wordpressuser1
      WORDPRESS_DB_PASSWORD: wordpresspw1
      WORDPRESS_DB_NAME: wordpressdb1
    working_dir: /var/www/html/wp1
    volumes:
      - ./wp1:/var/www/html/wp1
  wp2:
    depends_on:
      - db2
    environment:
      WORDPRESS_DB_HOST: db2:3306
      WORDPRESS_DB_USER: wordpressuser2
      WORDPRESS_DB_PASSWORD: wordpresspw2
      WORDPRESS_DB_NAME: wordpressdb2
    working_dir: /var/www/html/wp2
    volumes:
      - ./wp2:/var/www/html/wp2

  # nginx
  web:
    depends_on:
      - wp1
      - wp2
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./logs1:/var/log/nginx/wp1
      - ./logs2:/var/log/nginx/wp2
      - ./wp1:/var/www/html/wp1
      - ./wp2:/var/www/html/wp2
    ports:
      - 8000:8000
      - 8001:8001
  
  # visualizer
  visualizer:
    image: dockersamples/visualizer
    ports:
      - 9999:8080
